name: Test External

on: [push, pull_request]

permissions:
  contents: read

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        ruby: ['3.1', '3.2', '3.3']

    runs-on: ${{matrix.os}}
    env:
      CI: external
      BUNDLER_VERSION: 2.4.22

    steps:
    - uses: actions/checkout@v4

    - uses: ruby/setup-ruby-pkgs@v1
      with:
        ruby-version: ${{matrix.ruby}}
        bundler: 2.4.22
        bundler-cache: true
        apt-get: _update_ libfcgi-dev libmemcached-dev
        brew: fcgi libmemcached

    # Install pandoc:
    - run: sudo apt-get install -y pandoc

    - run: bundle exec bake test:external
