name: Test External

on: [push, pull_request]

permissions:
  contents: read

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        ruby: ['3.2', '3.3']

    runs-on: ${{matrix.os}}
    env:
      CI: external
      BUNDLER_VERSION: 2.5.12

    steps:
    - uses: actions/checkout@v4

    - uses: ruby/setup-ruby-pkgs@v1
      with:
        ruby-version: ${{matrix.ruby}}
        bundler: 2.5.12
        bundler-cache: true
        apt-get: _update_ libfcgi-dev libmemcached-dev
        brew: fcgi libmemcached

    - run: ls -latr /opt/hostedtoolcache/Ruby/3.2.5/x64/lib/ruby/gems/3.2.0/gems
      if: matrix.ruby == '3.2'

    - run: ls -latr /opt/hostedtoolcache/Ruby/3.3.4/x64/lib/ruby/gems/3.3.0/gems
      if: matrix.ruby == '3.3'

    # Install pandoc:
    - run: sudo apt-get install -y pandoc

    - run: bundle exec bake test:external
